"""
Report Agent.

Compiles a structured, persisted report document from everything gathered
during the agent run (inventory, shipment, knowledge, risk, recommendation
findings). Only runs when the Planner decided the user wants a report/export.
"""
from __future__ import annotations

from typing import Any, Dict, List

from app.agents.state import CopilotState
from app.database import COLL_REPORTS, get_db
from app.models.schemas import Report
from app.services.bedrock_client import get_bedrock_client
from app.utils.logger import get_logger

logger = get_logger(__name__)

REPORT_SYSTEM_PROMPT = """You are the Report Agent in an AI Supply Chain \
Copilot. Compile a structured executive report from the supplied findings. \
Respond with ONLY JSON in this exact shape:
{"title": "...", "summary": "2-3 sentence executive summary", \
"sections": [{"heading": "...", "body": "..."}]}
Sections should typically include: Inventory Status, Shipment Status, \
Risk Assessment, Recommendations — but only include sections that have \
supporting findings."""


async def report_node(state: CopilotState) -> Dict[str, Any]:
    db = get_db()
    context = _build_context(state)

    bedrock = get_bedrock_client()
    result = await bedrock.generate_json(prompt=context, system=REPORT_SYSTEM_PROMPT)

    title = result.get("title") or "Supply Chain Status Report"
    summary = result.get("summary") or "Automated report generated by the AI Supply Chain Copilot."
    sections = result.get("sections", []) if not result.get("_parse_error") else _fallback_sections(state)

    report = Report(title=title, summary=summary, sections=sections)
    await db[COLL_REPORTS].insert_one(report.model_dump())

    logger.info("report_agent.completed", report_id=report.report_id, sections=len(sections))

    remaining = [a for a in state.get("remaining_agents", []) if a != "report"]

    return {
        "report": report.model_dump(mode="json"),
        "remaining_agents": remaining,
        "traces": [
            {
                "agent": "report",
                "action": "compile_report",
                "output_summary": f"Compiled report '{title}' with {len(sections)} section(s).",
            }
        ],
    }


def _build_context(state: CopilotState) -> str:
    parts = [f"User request: {state['user_message']}", f"Final answer so far: {state.get('final_answer', '')}"]
    for finding in state.get("inventory_findings", []):
        parts.append(f"Inventory: {finding.get('summary', '')}")
    for finding in state.get("shipment_findings", []):
        parts.append(f"Shipment: {finding.get('summary', '')}")
    for finding in state.get("knowledge_findings", []):
        parts.append(f"Knowledge: {finding.get('summary', '')}")
    for finding in state.get("risk_findings", []):
        parts.append(f"Risk: {finding.get('narrative', '')}")
    if state.get("recommendations"):
        recs = "; ".join(r.get("title", "") for r in state["recommendations"])
        parts.append(f"Recommendations: {recs}")
    return "\n\n".join(parts)


def _fallback_sections(state: CopilotState) -> List[Dict[str, Any]]:
    sections = []
    if state.get("inventory_findings"):
        sections.append({"heading": "Inventory Status", "body": state["inventory_findings"][0].get("summary", "")})
    if state.get("shipment_findings"):
        sections.append({"heading": "Shipment Status", "body": state["shipment_findings"][0].get("summary", "")})
    if state.get("risk_findings"):
        sections.append({"heading": "Risk Assessment", "body": state["risk_findings"][0].get("narrative", "")})
    if state.get("recommendations"):
        body = "\n".join(f"- {r.get('title')}: {r.get('rationale')}" for r in state["recommendations"])
        sections.append({"heading": "Recommendations", "body": body})
    return sections
